# Generated by Django 5.1.4 on 2024-12-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userstock_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstockfollowed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
