# Generated by Django 5.1.4 on 2025-01-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_userstockfollowed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
