# Generated by Django 5.1.4 on 2024-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('marketPrice', models.FloatField()),
                ('sectionIndex', models.CharField(max_length=255)),
                ('details', models.JSONField()),
            ],
        ),
    ]
